// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb53Gb_kFv8bAHsdssn9s_F6Rr-Aj4Iwg',
    appId: '1:912687969284:web:e266f2b0611e301af27151',
    messagingSenderId: '912687969284',
    projectId: 'flutterapp-49b80',
    authDomain: 'flutterapp-49b80.firebaseapp.com',
    storageBucket: 'flutterapp-49b80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqAXAFkH-fCJ4RtmAX2RK2GMiTTZHDwtQ',
    appId: '1:912687969284:android:9ab477b6a35e86d4f27151',
    messagingSenderId: '912687969284',
    projectId: 'flutterapp-49b80',
    storageBucket: 'flutterapp-49b80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALqijneAJcaFT-NCpGFOIWDMnIj8N35ig',
    appId: '1:912687969284:ios:e9fc4c86735462f3f27151',
    messagingSenderId: '912687969284',
    projectId: 'flutterapp-49b80',
    storageBucket: 'flutterapp-49b80.firebasestorage.app',
    iosBundleId: 'com.example.moreExperts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALqijneAJcaFT-NCpGFOIWDMnIj8N35ig',
    appId: '1:912687969284:ios:e9fc4c86735462f3f27151',
    messagingSenderId: '912687969284',
    projectId: 'flutterapp-49b80',
    storageBucket: 'flutterapp-49b80.firebasestorage.app',
    iosBundleId: 'com.example.moreExperts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb53Gb_kFv8bAHsdssn9s_F6Rr-Aj4Iwg',
    appId: '1:912687969284:web:e96a9c48752e7039f27151',
    messagingSenderId: '912687969284',
    projectId: 'flutterapp-49b80',
    authDomain: 'flutterapp-49b80.firebaseapp.com',
    storageBucket: 'flutterapp-49b80.firebasestorage.app',
  );
}